spring:
  main.allow-bean-definition-overriding: true
  profiles:
    active: local
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy
        implicit-strategy: org.springframework.boot.orm.jpa.hibernate.SpringImplicitNamingStrategy
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect


logging:
  level:
    ROOT: info
    org.hibernate.type.descriptor.sql.BasicBinder: trace

server:
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
